
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/chaos_prod?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=PRC&allowPublicKeyRetrieval=true
      username: root
      password: 12345678
